l_english:
#mustafa+
impart_values.0001.t:0 "Hayat Boyu Unutulmayacak Bir Ders Aşılamak"
impart_values.0001.desc:0 "#italic Ahh, genç olmak, enerji ve coşku dolu olmak. Önünüzde keşfedilmeyi bekleyen bütün bir dünya. Ve kendi kişiliğiniz, kendiniz için bile bir gizem.#!\n\n[recipient.GetTitledFirstName], benim [recipient.Custom('InsultAdjective')] [ROOT.Char.Custom2('RelationToMePossessiveShort', recipient)], her zamanki dikkatsizliğiyle içeri girdiğinde gençliğin bu değişkenliği üzerine düşünürken buluyorum kendimi.\n\nOnu görmek içimde bir şeyi harekete geçiriyor: #bold Bu çocuğa hayatta neyin önemli olduğu konusunda bir ders vereceğim.#!"
already_imparted_lesson_desc:0 "[CHARACTER.GetShortUINameNoTooltip] adlı kişiyehayatta neye değer vermesi gerektiğini öğretmeye daha önce çalışmıştınız."
impart_values.0001.diligent:0 "[recipient.GetSheHe], azimli ve sıkı çalışmanın her zaman kendisine yardımcı olacağını öğrenecek."
impart_values.0001.lazy:0 " [recipient.GetFirstName], işleri başkalarının halletmesine izin vermeyi öğrenmeli."
impart_values.0001.cynical:0 "Onun başkalarının niyetlerini her zaman sorgulamayı öğrenmesi gerekiyor."
impart_values.0001.zealous:0 "O inancın en önemli şey olduğunu bilmeli."
impart_values.0001.brave:0 "[recipient.GetFirstName], her düşmana karşı korkusuz olmayı öğrenecek."
impart_values.0001.craven:0 "Tüm korkulardan saklanmak, dikkat edilmesi gereken akıllıca bir derstir."
impart_values.0001.calm:0 "[recipient.GetFirstName] sakin kalmanın önemini bilmeli."
impart_values.0001.wrathful:0 "Ona öfke ve hiddetle hareket etmeyi öğreteceğim."
impart_values.0001.chaste:0 "[recipient.GetFirstName], doğal arzuların her türlü cazibesinden kaçınmalıdır."
impart_values.0001.lustful:0 "[recipient.GetFirstName], doğal arzularını kucaklamayı öğrenmelidir."
impart_values.0001.content:0 "Ona sahip olduklarıyla yetinmeyi öğreteceğim."
impart_values.0001.ambitious:0 "Ona hırsın önemini öğreteceğim."
impart_values.0001.fickle:0 "Ona değişen bir zihnin arzu edilen bir özellik olduğunu öğreteceğim."
impart_values.0001.stubborn:0 "Ona hiçbir muhalefete karşı asla geri adım atmaması öğretilecek."
impart_values.0001.forgiving:0 "[recipient.GetSheHe], başkalarına merhamet göstermenin önemini öğrenecek."
impart_values.0001.vengeful:0 "Ona kendisine yanlış yapanları asla unutmamayı öğreteceğim."
impart_values.0001.generous:0 "Ona hayırseverlik eylemlerinin sonsuz anlamlı olduğunu göstereceğim."
impart_values.0001.greedy:0 "Kişinin cüzdanına sıkı sıkıya sarılması her zaman öğrenilecek iyi bir derstir."
impart_values.0001.gregarious:0 "Ona başkalarının arkadaşlığının sevinçlerini göstereceğim."
impart_values.0001.shy:0 "Ona yalnız olmanın huzurlu faydalarını öğreteceğim."
impart_values.0001.honest:0 "[recipient.GetSheHe], doğruluk ve samimiyetin temel değerler olduğunu öğrenecek."
impart_values.0001.deceitful:0 "Ona nefes almak kadar kolay yalan söylemeyi öğreteceğim."
impart_values.0001.humble:0 "Mütevazı bir yaşam, Onun öğrenebileceği basit bir zevktir."
impart_values.0001.arrogant:0 "[recipient.GetSheHe], öz değer duygusunun her şeyden üstün olduğunu öğrenecek."
impart_values.0001.just:0 "Ona tanrıların ve insanların yasalarına uymayı öğreteceğim."
impart_values.0001.arbitrary:0 "Başkalarına bakmaksızın kendi bildiklerini yapmayı öğrenmeliler."
impart_values.0001.patient:0 "Ona sabrın önemini aşılayacağım."
impart_values.0001.impatient:0 "Ona sonuçları görmekte gecikme olduğunda huzursuz olmayı öğreteceğim."
impart_values.0001.temperate:0 "[recipient.GetSheHe], her şeyin ölçülü alınması gerektiğini öğrenecek."
impart_values.0001.gluttonous:0 "[recipient.GetFirstName], zevkli olan her şeyin bolluğuna boğulmalıdır."
impart_values.0001.trusting:0 "[recipient.GetSheHe], etrafındakilere güvenmeyi öğrenecek."
impart_values.0001.paranoid:0 "[recipient.GetFirstName] her zaman arkasını kollamayı öğrenmelidir."
impart_values.0001.compassionate:0 "[recipient.GetFirstName] her şeyden önce şefkatli olmayı bilmeli."
impart_values.0001.callous:0 "Başkalarının sorunlarını görmezden gelmek Ona iyi hizmet edecektir."
impart_values.0001.sadistic:0 "Ona başkalarına acı çektirmekten zevk almayı öğreteceğim."
impart_values.0001.rude:0 "Ona ne kadar açık sözlü olursa olsun aklından geçenleri söylemeyi öğreteceğim."
impart_values.0001.honorable:0 "Ona ahlaklı olmasını, saygı görmesi gerektiğini öğreteceğim."
impart_values.0001.ruthless:0 "[recipient.GetSheHe], hedeflerine ulaşmak için acımasız olmayı öğrenecek."
impart_values.0001.authoritative:0 "Ona otoriter olmanın önemini öğreteceğim."
impart_values.0001.inquisitive:0 "[recipient.GetSheHe], bilgi edinmenin değerini öğrenecek."
impart_values.0001.backout:0 "Boş ver, Onun hazır olduğunu düşünmüyorum."
impart_values_lesson_ignored_title:0 "Ders Görmezden Gelindi"
impart_values_lesson_ignored_desc:0 "[recipient.GetShortUINameNoTooltip], derslerinize ilgi göstermedi."
impart_values_lesson_success_title:0 "Ders Başarılı"
impart_values_lesson_success_desc:0 "[recipient.GetShortUINameNoTooltip], derslerinizi ciddiye aldı ve [recipient.Custom('TraitLearned')] özelliğini kazandı."
impart_values_lesson_failure_title:0 "Ders Başarısız"
impart_values_lesson_failure_desc:0 "[recipient.GetShortUINameNoTooltip], derslerinize karşı çıktı ve [recipient.Custom('TraitLearned')] özelliğini kazandı."